import fs from 'bare-fs';
import path from 'bare-path';
import { publicDir, htmlPath, ensureDirs } from '../paths.mjs';
import { MIN_PUBLISHED_GROUP } from '../db.mjs';

// Render the data-protection pages that the published site needs:
//
//   privacy.html                 the Art. 14 information notice
//   scanner.html                 "one of our nodes connected to you" — the page
//                                a sysadmin lands on after a reverse lookup
//   .well-known/security.txt     RFC 9116 contact record
//
// Why a notice at all: we collect data about people who never visited the site,
// so GDPR Art. 14 applies rather than Art. 13. Notifying each peer individually
// is impossible (the DHT carries no such channel and we hold no contact
// details), which is exactly the case Art. 14(5)(b) covers — but that exemption
// is conditional on publishing the information instead. This page IS that
// condition being met, not a courtesy.
//
// The scanner page follows the convention set by Shodan, Censys and RIPE Atlas:
// point the crawler IP's reverse DNS at a page that explains who is connecting
// and how to be excluded, so the answer reaches an annoyed sysadmin before a
// complaint does.

// ---------------------------------------------------------------------------
// The one site-specific value: an email address, and nothing else. The pages
// deliberately do NOT identify an operator or carry a site URL — every link
// between them is relative, so the pages work from any host without being
// configured for one. This address is the abuse / exclusion contact, which the
// scanner page and security.txt need in order to do their job at all (RFC 9116
// makes `Contact` mandatory, and "write to us to be excluded" without an
// address is not an offer). Fill it in before publishing.
// ---------------------------------------------------------------------------
const CONTACT_EMAIL = '[contact]';

const PLACEHOLDER = /^\[.*\]$/;

// Data-protection facts that are properties of the code, kept here so the page
// and the repo docs can't drift apart silently.
const RETENTION_OBSERVATION_DAYS = 14;
const RETENTION_NODE_HOURS = 72;
const SALT_ROTATION = 'monthly';

const TILE_PROVIDER = 'CARTO (basemaps.cartocdn.com)';

// --- theme (matches index.mjs) ------------------------------------------------
const BG = '#060a08';
const PANEL = 'rgba(8,16,12,0.82)';
const TEXT = '#eafff2';
const MUTED = '#5f7d6e';
const GRID = 'rgba(120,200,150,0.10)';
const ACCENT = '#b6ff3c';

const STYLE = `
    html, body { margin: 0; min-height: 100%; background: ${BG};
      color: ${TEXT}; font-family: Inter, system-ui, -apple-system, sans-serif;
      -webkit-font-smoothing: antialiased; }
    .wrap { max-width: 780px; margin: 0 auto; padding: 40px 22px 64px; }
    a { color: ${ACCENT}; }
    h1 { font-size: 25px; font-weight: 600; margin: 0 0 6px; }
    h2 { font-size: 16px; font-weight: 600; margin: 32px 0 8px;
      padding-top: 14px; border-top: 1px solid ${GRID}; }
    h3 { font-size: 13.5px; font-weight: 600; margin: 18px 0 6px;
      color: ${ACCENT}; }
    p, li { font-size: 14px; line-height: 1.7; color: #cfe8dc; }
    li { margin-bottom: 5px; }
    .lede { color: ${MUTED}; font-size: 14px; line-height: 1.7;
      margin: 0 0 8px; }
    code { font-size: 12.5px; color: ${ACCENT}; }
    table { border-collapse: collapse; width: 100%; margin: 10px 0 4px;
      font-size: 13px; }
    th, td { text-align: left; padding: 7px 10px; vertical-align: top;
      border-bottom: 1px solid ${GRID}; }
    th { color: ${MUTED}; font-weight: 500; font-size: 11.5px;
      text-transform: uppercase; letter-spacing: .4px; }
    .box { background: ${PANEL}; border: 1px solid ${GRID};
      border-radius: 10px; padding: 14px 18px; margin: 16px 0; }
    .box.warn { border-color: rgba(232,198,90,.35); }
    .nav { font-size: 12.5px; color: ${MUTED}; margin-bottom: 26px; }
    footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid ${GRID};
      color: ${MUTED}; font-size: 12px; line-height: 1.7; }`;

function page({ title, body }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${title} · hyperdht-explorer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>${STYLE}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="nav"><a href="index.html">← hyperdht-explorer</a></div>
${body}
    <footer>
      This page is generated by <code>hyperdht-explorer render:privacy</code>
      and describes the behaviour of the code that produced the reports
      alongside it. It is information about a specific deployment, not legal
      advice, and not a warranty about anyone else's copy of the software.
    </footer>
  </div>
</body>
</html>
`;
}

function privacyBody() {
  return `    <h1>Privacy notice</h1>
    <p class="lede">
      How this service handles personal data — both data about peers on the
      hyperdht network, and data about people who visit these pages.
    </p>

    <h2>1. What this service does</h2>
    <p>
      hyperdht-explorer measures the health of a public peer-to-peer network:
      how many nodes there are, where they sit, how reliable they are, and how
      much of the network is run on end-user machines rather than in
      datacenters. It does this by taking part in that network the way any other
      participant does — walking the routing table, pinging nodes, and seeding
      public application update feeds — and recording what it sees in
      aggregate.
    </p>
    <p>
      It does not attempt to identify people, and the data it keeps is not
      capable of doing so on its own. There is no advertising, no profiling, no
      automated decision-making, and nothing is sold or shared with anyone.
    </p>

    <h2>2. Data about network participants</h2>
    <p>
      Two kinds of peer are recorded, and they are treated differently.
    </p>

    <h3>Routing nodes</h3>
    <table>
      <tr><th>What</th><td>The IPv4 address and port of nodes in the DHT
        routing table, when we first and last saw them, how often, and whether
        they answered a ping and how quickly.</td></tr>
      <tr><th>Source</th><td>The public DHT itself. These addresses are
        broadcast to every participant by design — that is how the network
        routes.</td></tr>
      <tr><th>Why</th><td>Counting nodes, measuring liveness and churn, and
        mapping the network's geographic and operator distribution.</td></tr>
      <tr><th>Kept for</th><td>${RETENTION_NODE_HOURS} hours since last sighting;
        stale rows are deleted on each crawl.</td></tr>
      <tr><th>Published?</th><td>No. Individual addresses are never published.
        Reports show networks (/24) and aggregates only.</td></tr>
    </table>

    <h3>Connecting peers</h3>
    <table>
      <tr><th>What</th><td>The <em>network</em> (/24) a peer connected from —
        never the full address, never the port — a pseudonym derived from its
        public key, which public application feed it was using, first and last
        seen, and a connection count.</td></tr>
      <tr><th>Source</th><td>Peers that connect to our node while it seeds a
        public application update feed. We do not initiate these
        connections.</td></tr>
      <tr><th>Why</th><td>Counting real participants — including those behind
        home and mobile connections, who never appear in the routing table — to
        tell how much of the network is genuine end-user activity.</td></tr>
      <tr><th>Kept for</th><td>${RETENTION_OBSERVATION_DAYS} days since last
        sighting.</td></tr>
      <tr><th>Published?</th><td>Only as counts per network, country and
        application.</td></tr>
    </table>

    <div class="box">
      <b>On the pseudonym.</b> A peer's public key is never stored. It is
      passed through a keyed hash whose secret salt rotates ${SALT_ROTATION} and
      is then destroyed. Within one month we can tell that two connections came
      from the same peer, which is what "distinct participants" means. Across
      months we cannot, and once a salt is destroyed neither can anyone else,
      including us — the stored rows can no longer be worked back to a peer at
      all.
    </div>

    <h3>Requests our node receives</h3>
    <p>
      Once our node has been online long enough, other peers route their own DHT
      work through it, exactly as they do through every other node. We count
      those requests — how many arrived, and which of the protocol's commands
      each one was — to measure whether the network is actually being used
      rather than merely existing.
    </p>
    <div class="box">
      <b>Counters only.</b> Each request also says <em>what</em> it is asking
      for: which topic or record is being looked up or advertised. We count how
      <em>many different</em> things were asked for, because a network where
      everyone looks up something different is a different network from one
      where a few things are looked up constantly. We do not record
      <em>which</em>, and we are not able to: each one is put through a one-way
      fingerprint under a secret that is generated fresh for each measurement
      and never saved, so the fingerprints cannot be matched against any topic,
      by us or by anyone who obtained them. Only the resulting count is kept.
    </div>
    <p>
      Nothing is stored per peer, and nothing per request — no address, no key,
      no request contents. Unlike everything else on this page, there is no row
      here to retain, to delete, or to exclude a network from, because none is
      ever created. The stored result of an hour of this is a handful of numbers
      like "8,200 requests, of which 1,040 were lookups, asking for 320
      different things".
    </p>

    <h3>What is never collected</h3>
    <ul>
      <li>Message content, chat rooms, file contents or anything private. Only
        public application update feeds are seeded, and those are signed by the
        application publisher.</li>
      <li>Names, email addresses, accounts or any contact details.</li>
      <li>Full addresses of connecting peers, at any point after the connection
        itself.</li>
      <li>Anything from private, reserved or non-routable address ranges.</li>
      <li>What anyone is looking up or advertising on the DHT. Our node handles
        those requests like any other node, and counts them — including how many
        different things were asked for — but never records, and cannot
        reconstruct, what any of them were.</li>
    </ul>

    <h3>Legal basis</h3>
    <p>
      Legitimate interests — Art. 6(1)(f). The interest is understanding the
      health and decentralisation of a public network that people rely on, which
      cannot be measured from outside it. Consent is not workable (there is no
      channel to ask a routing table entry for it, and asking would bias the
      measurement), and no contract exists with these peers.
    </p>
    <p>
      That basis requires the interest to be balanced against the rights of the
      people involved. The measures on this page — addresses reduced to
      networks, keys replaced by rotating pseudonyms, short retention, nothing
      identifiable published, an exclusion mechanism that is honoured in code —
      are the outcome of that balancing, which is documented in the repository.
    </p>

    <h3>Who receives it</h3>
    <p>
      Nobody. The data stays on the operator's own machine. Two third-party
      lookups happen during processing, and neither receives anything about you
      beyond the address being looked up:
    </p>
    <ul>
      <li><b>ip-api.com</b> — one lookup per /24 network to get country, city
        and operator. This is a database query, not a probe: nothing is sent to
        the address itself.</li>
      <li><b>RIPEstat</b> (RIPE NCC, Netherlands) — public BGP and RPKI
        information about network prefixes and autonomous systems.</li>
    </ul>

    <h2>3. Data about visitors to this site</h2>
    <p>
      These pages are static files. There are <b>no cookies, no analytics, no
      trackers and no fingerprinting</b>, so there is no cookie banner to click
      — there is nothing to consent to. Nothing you do here is recorded by us
      beyond ordinary web server logs.
    </p>
    <p>
      All scripts and stylesheets are served from this site rather than from a
      content delivery network, specifically so that loading a page does not
      disclose your IP address to a third party.
    </p>
    <div class="box warn">
      <b>One exception:</b> the world map loads its background tiles from
      ${TILE_PROVIDER}, which cannot practically be self-hosted. Opening
      <code>map.html</code> therefore discloses your IP address to that
      provider. The page sends no referrer, so they do not learn which page you
      were viewing. Every other report works with no third-party requests at
      all.
    </div>

    <h2>4. Publication and aggregation</h2>
    <p>
      Reports are published as counts grouped by network, operator, autonomous
      system and country. In addition, a residential or mobile network with
      fewer than ${MIN_PUBLISHED_GROUP} participants is shown only as its wider
      /16 with the city withheld, because naming a single end-user subnet in a
      small town comes uncomfortably close to naming a household. Totals are
      unaffected.
    </p>

    <h2>5. Your rights</h2>
    <p>
      Under the GDPR you have the right to access your data, to have it
      corrected or erased, to restrict how it is used, and — because the
      processing rests on legitimate interests — to <b>object to it at any
      time</b> (Art. 21).
    </p>

    <h3>Objecting / being excluded</h3>
    <p>
      Write to <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a> with
      the IP address or network you want excluded. On request we will add the
      network to an exclusion list, which:
    </p>
    <ul>
      <li>deletes everything already stored about it, across every table, and</li>
      <li>prevents it from being recorded again — enforced at the point of
        writing to the database, so no part of the software can bypass it.</li>
    </ul>
    <p>
      Please note the practical limits, stated plainly rather than buried: the
      unit of exclusion is the /24 network, because that is the finest
      granularity anything here stores. And because we hold no identifier that
      links to you as a person, we generally cannot tell which rows are "yours"
      other than by the network you tell us about — which is also why an access
      request will usually be answered with the rows for a network you name.
    </p>

    <h2>6. Anyone else running this software</h2>
    <p>
      hyperdht-explorer is open source and anyone can run their own copy. This
      notice covers only the deployment that published this page. Whoever runs
      another instance is responsible for that instance's data, and this notice
      says nothing about what they do.
    </p>

    <h2>7. Changes</h2>
    <p>
      Material changes will be reflected on this page. The behaviour it
      describes is enforced by the published source code, so the source history
      is the authoritative record of when something changed.
    </p>`;
}

function scannerBody() {
  return `    <h1>A node from this service connected to you</h1>
    <p class="lede">
      You probably arrived here from a firewall log or a reverse DNS lookup.
      Here is exactly what happened, and how to make it stop.
    </p>

    <h2>What this is</h2>
    <p>
      hyperdht-explorer is a research crawler that measures the health of
      <b>hyperdht</b>, the public peer-to-peer network behind Holepunch / Pear
      applications. It takes part in that network the way any other participant
      does. If our node contacted yours, one of these happened:
    </p>
    <ul>
      <li>Your address was in the DHT's public routing table and we sent a
        <code>find_node</code> or <code>ping</code> — the same messages every
        other peer on the network sends.</li>
      <li>Your peer connected to <em>us</em> while we were seeding a public
        application update feed, and we served you data.</li>
      <li>Your node sent <em>us</em> a request, because our node was in your
        routing table. We answered it, the way any node answers any other.</li>
    </ul>

    <h2>What it is not</h2>
    <ul>
      <li>Not a port scan. We only speak the DHT protocol, to the port your node
        advertised.</li>
      <li>Not a vulnerability scan, and not an attack. No exploit is attempted
        and nothing is probed beyond liveness.</li>
      <li>Not an attempt to identify you. Peer public keys are never stored,
        connecting peers' addresses are reduced to their /24, and individual
        addresses are never published.</li>
      <li>Not surveillance of what you are looking up. Requests our node
        receives are counted by type, and we count how many different things
        were asked for — but each is fingerprinted one-way under a secret that
        is discarded at the end of the measurement, so which they were is not
        stored and cannot be recovered.</li>
    </ul>

    <h2>Make it stop</h2>
    <p>
      Send the IP address or network to
      <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>. We will
      exclude it: everything stored about it is deleted and it will not be
      recorded again. No justification needed, and no reply expected from you
      beyond the address.
    </p>
    <p>
      Note that exclusion stops <em>our</em> records and our contact. It cannot
      stop other DHT participants from reaching your node — if you want that,
      the node itself needs to stop announcing.
    </p>

    <h2>More</h2>
    <p>
      Full details of what is collected and why are in the
      <a href="privacy.html">privacy notice</a>. The reports produced from this
      data are <a href="index.html">here</a>, and the source code is public.
    </p>`;
}

// RFC 9116. `Contact` and `Expires` are the mandatory fields and both are here;
// Expires must be in the future, and a year out is the usual choice —
// re-rendering (which the cron does every cycle) rolls it forward.
//
// `Canonical` and `Policy` are omitted rather than guessed: both must be
// absolute URIs, and we deliberately hold no site URL. They are optional, so
// leaving them out keeps the record valid; a reader who wants the policy is one
// relative link away on the site they already found this on.
function securityTxt(now) {
  const expires = new Date(now);
  expires.setUTCFullYear(expires.getUTCFullYear() + 1);
  return `# hyperdht-explorer — security and abuse contact
# If one of our nodes contacted yours, see /scanner.html on this site.

Contact: mailto:${CONTACT_EMAIL}
Expires: ${expires.toISOString().replace(/\.\d{3}Z$/, 'Z')}
Preferred-Languages: en
`;
}

// An exclusion offer addressed to [CONTACT EMAIL] is not an offer, and an
// RFC 9116 record with a placeholder Contact is invalid. Fail loudly at render
// time rather than letting either reach the web server.
function warnPlaceholders() {
  if (!PLACEHOLDER.test(CONTACT_EMAIL)) {
    return;
  }
  console.error(
    '\n!! privacy: CONTACT_EMAIL is still the placeholder ' +
      `'${CONTACT_EMAIL}'`
  );
  console.error(
    '!! Set it in commands/privacy.mjs before publishing these pages.\n'
  );
}

export function run() {
  ensureDirs();

  const pages = [
    ['privacy.html', page({ title: 'Privacy notice', body: privacyBody() })],
    ['scanner.html', page({ title: 'About this scanner', body: scannerBody() })]
  ];
  for (const [file, html] of pages) {
    fs.writeFileSync(htmlPath(file), html);
    console.log(`privacy: wrote ${file}`);
  }

  const wellKnown = path.join(publicDir(), '.well-known');
  fs.mkdirSync(wellKnown, { recursive: true });
  fs.writeFileSync(
    path.join(wellKnown, 'security.txt'),
    securityTxt(Date.now())
  );
  console.log('privacy: wrote .well-known/security.txt');

  warnPlaceholders();
  console.log(`open it in a browser:  file://${htmlPath('privacy.html')}`);
}
